import cv2  # OpenCV library for all computer vision and image processing tasks
import numpy as np  # NumPy for high-performance matrix mathematics and array manipulation
import rclpy  # ROS 2 Python client library (handles nodes, topics, etc.)
from rclpy.node import (
    Node,
)  # The base Node class we inherit from to create a ROS 2 node
from sensor_msgs.msg import (
    Image,
)  # Standard ROS 2 message type for transmitting uncompressed images
from std_msgs.msg import (
    Int32,
)  # Standard ROS 2 message type for sending single integers
from cv_bridge import (
    CvBridge,
)  # A bridge library that translates ROS 2 Image messages into OpenCV format
from rcl_interfaces.msg import (
    SetParametersResult,
)  # Required for the dynamic parameter server callback


class BevNode(Node):
    """
    A ROS 2 Node that subscribes to a camera feed, applies an advanced
    Bird's-Eye View (BEV) perspective transform, detects lane lines using
    combined color/gradient thresholding and a sliding window algorithm,
    and outputs proportional steering and motor speed commands.
    """

    def __init__(self):
        # Initialize the underlying ROS 2 node with the name 'bev_node'
        super().__init__("bev_node")

        # ---------------------------------------------------------
        # 1. ROS 2 INFRASTRUCTURE SETUP
        # ---------------------------------------------------------
        # Initialize the CvBridge object which we will use in the image_callback
        self.bridge = CvBridge()

        # Subscribe to the camera topic.
        # Type: Image, Topic Name: "/image_raw", Callback: self.image_callback, Queue Size: 10
        self.subscription = self.create_subscription(
            Image, "/image_raw", self.image_callback, 10
        )

        # Publishers to send commands to your physical hardware via the motor_control node
        # Queue size of 10 ensures we don't drop commands if the serial port briefly lags
        self.steering_pub = self.create_publisher(Int32, "/servo/steering_angle", 10)
        self.motor_pub = self.create_publisher(Int32, "/motor/speed", 10)

        # ---------------------------------------------------------
        # 2. DYNAMIC PARAMETER SERVER
        # ---------------------------------------------------------
        # Declaring parameters registers them with ROS 2 so they can be changed
        # on the fly using terminal commands or rqt_reconfigure.

        # kp: Proportional gain. How aggressively the car steers to correct an error.
        self.declare_parameter("kp", 0.2)
        # base_speed: The constant forward speed applied to the DC motors.
        self.declare_parameter("base_speed", 40)
        # center_steering: The neutral, straight-ahead angle for your front servo.
        self.declare_parameter("center_steering", 90)

        # lane_target_ratio: Tells the car where to keep the center yellow line in its view.
        # 0.25 means "keep the yellow line 25% of the way from the left edge of the screen",
        # which effectively forces the car to drive perfectly in the right-hand lane.
        self.declare_parameter("lane_target_ratio", 0.25)

        # Retrieve the initial values assigned above and store them as class variables
        self.kp = self.get_parameter("kp").value
        self.base_speed = self.get_parameter("base_speed").value
        self.center_steering = self.get_parameter("center_steering").value
        self.lane_target_ratio = self.get_parameter("lane_target_ratio").value

        # Register the callback function that listens for incoming parameter changes
        self.add_on_set_parameters_callback(self.parameter_callback)

        # ---------------------------------------------------------
        # 3. CAMERA CALIBRATION MATRICES (INTRINSICS)
        # ---------------------------------------------------------
        # These matrices are generated by calibrating your specific camera lens
        # with a checkerboard. They map the 3D world to your 2D image sensor.

        # The Camera Matrix (mtx) contains the focal lengths (fx, fy) and optical centers (cx, cy).
        # Format: [[fx,  0, cx],
        #          [ 0, fy, cy],
        #          [ 0,  0,  1]]
        self.camera_matrix = np.array(
            [[500.123, 0.0, 320.5], [0.0, 500.456, 240.2], [0.0, 0.0, 1.0]]
        )

        # The Distortion Coefficients (dist) map radial and tangential distortion (the "fisheye" effect).
        # Format: [k1, k2, p1, p2, k3]
        self.dist_coeffs = np.array([[-0.123, 0.045, -0.001, 0.002, -0.003]])

    def parameter_callback(self, params):
        """
        This function is automatically triggered by ROS 2 whenever a user changes a parameter.
        It iterates through the changed parameters and updates the internal class variables.
        """
        for param in params:
            if param.name == "kp":
                self.kp = param.value
            elif param.name == "base_speed":
                self.base_speed = param.value
            elif param.name == "center_steering":
                self.center_steering = param.value
            elif param.name == "lane_target_ratio":
                self.lane_target_ratio = param.value

        # Required by ROS 2 to acknowledge the update was successful
        return SetParametersResult(successful=True)

    def thresholding(self, img):
        """
        Combines two different computer vision techniques to isolate the lane lines
        in almost any lighting condition, ignoring shadows and bright spots.
        """
        # Convert from BGR (Blue, Green, Red) to HLS (Hue, Lightness, Saturation)
        # HLS is excellent because 'Saturation' measures color intensity independent of 'Lightness'
        hls = cv2.cvtColor(img, cv2.COLOR_BGR2HLS)

        # --- Technique 1: Color Thresholding ---
        # Isolate the Saturation channel (index 2)
        s_channel = hls[:, :, 2]
        # Create an empty black image of the same size
        s_binary = np.zeros_like(s_channel)
        # Turn pixels white (1) if their saturation is between 120 and 255 (highly saturated/colorful)
        s_binary[(s_channel >= 120) & (s_channel <= 255)] = 1

        # --- Technique 2: Gradient (Edge) Thresholding ---
        # Isolate the Lightness channel (index 1) to look for physical contrast
        l_channel = hls[:, :, 1]
        # Apply the Sobel operator in the X direction to find vertical edges (lane lines)
        sobelx = cv2.Sobel(l_channel, cv2.CV_64F, 1, 0)
        # Convert negative derivatives (going from light to dark) to absolute positive values
        abs_sobelx = np.absolute(sobelx)
        # Scale the pixel values back into a standard 8-bit image range (0-255)
        scaled_sobel = np.uint8(255 * abs_sobelx / np.max(abs_sobelx))

        # Create an empty black image for the gradient mask
        sxbinary = np.zeros_like(scaled_sobel)
        # Turn pixels white (1) if they represent a strong, but not extreme, vertical edge
        sxbinary[(scaled_sobel >= 20) & (scaled_sobel <= 100)] = 1

        # --- Combine the Techniques ---
        combined_binary = np.zeros_like(sxbinary)
        # Use a bitwise OR '|'. If the pixel was flagged by color OR by gradient, keep it.
        combined_binary[(s_binary == 1) | (sxbinary == 1)] = 255

        return combined_binary

    def sliding_window(self, binary_warped):
        """
        Maps the exact curvature of the lane line by sliding bounding boxes
        up the image and grouping the active pixels together.
        """
        # 1. Create a histogram by summing the white pixels in the bottom half of the image vertically.
        #    This creates a 1D array where peaks represent the physical base of the lane lines.
        histogram = np.sum(binary_warped[binary_warped.shape[0] // 2 :, :], axis=0)

        # Create a 3-channel (color) image out of the binary mask so we can draw green boxes on it later
        out_img = np.dstack((binary_warped, binary_warped, binary_warped))

        # 2. Histogram Splitting for Track Navigation
        #    Find the exact midpoint of the X-axis
        midpoint = int(histogram.shape[0] // 2)

        #    By only searching the first half ([:midpoint]) of the histogram,
        #    we guarantee the code locks onto the LEFT (center divider) yellow line,
        #    ignoring the right-hand outer track boundary entirely.
        current_x = np.argmax(histogram[:midpoint])

        # 3. Setup Window Hyperparameters
        nwindows = 9  # Number of boxes to stack vertically
        window_height = int(binary_warped.shape[0] / nwindows)  # Height of each box
        margin = 50  # Width of the box (current_x +/- 50 pixels)
        minpix = 40  # Minimum number of pixels required to recenter the next box

        # 4. Extract all Non-Zero (White) pixels from the image
        nonzero = binary_warped.nonzero()
        nonzeroy = np.array(nonzero[0])
        nonzerox = np.array(nonzero[1])

        # List to hold the indices of the pixels that fall inside our boxes
        lane_inds = []

        # 5. Slide the windows up the image
        for window in range(nwindows):
            # Calculate the top and bottom Y coordinates for this specific box
            win_y_low = binary_warped.shape[0] - (window + 1) * window_height
            win_y_high = binary_warped.shape[0] - window * window_height

            # Calculate the left and right X coordinates for this specific box
            win_x_low = current_x - margin
            win_x_high = current_x + margin

            # Draw the box visually on our debug image (in green)
            cv2.rectangle(
                out_img,
                (win_x_low, win_y_low),
                (win_x_high, win_y_high),
                (0, 255, 0),
                2,
            )

            # Identify which of our image's active pixels fall INSIDE this specific box boundary
            good_inds = (
                (nonzeroy >= win_y_low)
                & (nonzeroy < win_y_high)
                & (nonzerox >= win_x_low)
                & (nonzerox < win_x_high)
            ).nonzero()[0]

            # Save these pixel indices
            lane_inds.append(good_inds)

            # If we found enough pixels in this box, shift the X-center of the NEXT box
            # to be the mathematical mean (average) X-position of the pixels we just found.
            # This allows the boxes to follow the curve of the road.
            if len(good_inds) > minpix:
                current_x = int(np.mean(nonzerox[good_inds]))

        # Combine all the localized pixel indices into one massive array
        lane_inds = np.concatenate(lane_inds)

        # Extract the actual X and Y coordinates for all those good pixels
        x_coords = nonzerox[lane_inds]
        y_coords = nonzeroy[lane_inds]

        # Return the coordinates and our visual debug image
        return x_coords, y_coords, out_img

    def image_callback(self, msg):
        """
        The main processing loop. Runs every time the camera takes a picture.
        """
        # Convert ROS message to OpenCV matrix
        raw_image = self.bridge.imgmsg_to_cv2(msg, "bgr8")

        # Step 1: Remove lens distortion using calibration matrices
        cv_image = cv2.undistort(
            raw_image, self.camera_matrix, self.dist_coeffs, None, self.camera_matrix
        )
        h, w = cv_image.shape[:2]

        # ---------------------------------------------------------
        # PERSPECTIVE TRANSFORM (WARPING)
        # ---------------------------------------------------------
        # src_pts: Four points defining a trapezoid on the ground ahead of the car.
        # This trapezoid captures the perspective-skewed lane lines.
        src_pts = np.float32([[w * 0.2, h * 0.6], [w * 0.8, h * 0.6], [0, h], [w, h]])

        # dst_pts: Four points defining a perfect rectangle.
        # This tells OpenCV how to stretch the src_pts to make them look flat from above.
        dst_pts = np.float32([[0, 0], [w, 0], [0, h], [w, h]])

        # Calculate the transformation matrix and apply it to the image
        warp_matrix = cv2.getPerspectiveTransform(src_pts, dst_pts)
        birdseye = cv2.warpPerspective(cv_image, warp_matrix, (w, h))

        # ---------------------------------------------------------
        # ISOLATE LANE LINES
        # ---------------------------------------------------------
        # Get the binary mask combining color and edges
        binary_warped = self.thresholding(birdseye)

        # Find the pixels belonging to the center divider using the sliding windows
        x_coords, y_coords, sliding_window_img = self.sliding_window(binary_warped)

        # Ensure we actually found pixels before doing math on them to prevent a crash
        if len(x_coords) > 0:

            # ---------------------------------------------------------
            # POLYNOMIAL FITTING
            # ---------------------------------------------------------
            # Use numpy to fit a second-degree polynomial (a curve) to the pixels.
            # Equation: x = A*y^2 + B*y + C
            # fit_pixels contains [A, B, C]
            fit_pixels = np.polyfit(y_coords, x_coords, 2)

            # Generate a sequence of Y coordinates spanning the height of the image
            ploty = np.linspace(0, h - 1, h)

            # Plug those Y coordinates into our polynomial equation to get theoretical X coordinates
            fitx = fit_pixels[0] * ploty**2 + fit_pixels[1] * ploty + fit_pixels[2]

            # Stack them together and draw a red line on our debug image representing the mathematical curve
            pts = np.array([np.transpose(np.vstack([fitx, ploty]))], np.int32)
            cv2.polylines(sliding_window_img, pts, False, (0, 0, 255), 4)

            # ---------------------------------------------------------
            # TARGETING & STEERING CONTROL (P-CONTROLLER)
            # ---------------------------------------------------------
            # We care most about where the line is right in front of the car (bottom of the image).
            # We evaluate our polynomial equation at y_eval (the maximum Y value).
            y_eval = np.max(ploty)
            lane_bottom_x = (
                fit_pixels[0] * y_eval**2 + fit_pixels[1] * y_eval + fit_pixels[2]
            )

            # Calculate our physical target.
            # w * 0.25 means the car wants the line 25% of the way from the left.
            target_x = w * self.lane_target_ratio

            # Proportional Error Calculation:
            # If the actual line (lane_bottom_x) is at pixel 300, and our target is pixel 160,
            # the error is +140.
            error_pixels = lane_bottom_x - target_x

            # Multiply the error by our tuning constant (Kp).
            # A positive error means we drifted left, so a positive adjustment steers us right.
            steering_adjustment = int(error_pixels * self.kp)

            # Add the adjustment to our physical center position
            final_angle = self.center_steering + steering_adjustment

            # Prevent the math from commanding an angle that would physically break the steering servo
            final_angle = max(45, min(135, final_angle))

            # ---------------------------------------------------------
            # PUBLISH HARDWARE COMMANDS
            # ---------------------------------------------------------
            servo_msg = Int32()
            servo_msg.data = final_angle
            self.steering_pub.publish(servo_msg)

            motor_msg = Int32()
            motor_msg.data = self.base_speed
            self.motor_pub.publish(motor_msg)

            # Visual Debugging: Draw a light blue vertical line representing our target ratio
            cv2.line(
                sliding_window_img,
                (int(target_x), 0),
                (int(target_x), h),
                (255, 255, 0),
                2,
            )

        else:
            # ---------------------------------------------------------
            # FAILSAFE (TRACK LOST)
            # ---------------------------------------------------------
            # If no pixels were found, stop the motors to prevent a collision
            self.get_logger().warn("Center divider lost! Halting.")
            stop_msg = Int32()
            stop_msg.data = 0
            self.motor_pub.publish(stop_msg)

        # ---------------------------------------------------------
        # RENDER DEBUG INTERFACE
        # ---------------------------------------------------------
        # Display the binary mask and the sliding window processing on screen
        # waitKey(1) is mandatory; it pauses the code for 1 millisecond allowing OpenCV to paint the GUI
        cv2.imshow("1. Combined Thresholding", binary_warped)
        cv2.imshow("2. Sliding Window Polyfit", sliding_window_img)
        cv2.waitKey(1)


def main(args=None):
    # Initialize the ROS 2 communications backbone
    rclpy.init(args=args)
    # Instantiate our Python class
    node = BevNode()
    try:
        # Keep the node alive, waiting for incoming camera frames infinitely
        rclpy.spin(node)
    except KeyboardInterrupt:
        # Handle the user pressing Ctrl+C in the terminal gracefully
        pass
    finally:
        # SHUTDOWN SEQUENCE:
        # 1. Send a final 0 speed command so the car doesn't drive away on its own
        stop_msg = Int32()
        stop_msg.data = 0
        node.motor_pub.publish(stop_msg)

        # 2. Close the OpenCV GUI windows
        cv2.destroyAllWindows()

        # 3. Cleanly destroy the ROS 2 node and shut down communications
        node.destroy_node()
        rclpy.shutdown()


# Standard Python boilerplate to run the main() function if this file is executed directly
if __name__ == "__main__":
    main()
